version = 0.1

[default]
[default.global.parameters]
stack_name = "PlayGrid"
s3_bucket = "folderas-cloudformation"
tags = ["resource-name=playgrid"]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
