AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

Parameters:
  StackName:
    Default: playgrid
    Description: Name of the CloudFormation stack
    Type: String

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: api/
      # Description: "String"
      # Environment: Environment
      Events:
        APIGateway:
          Properties:
            ApiId: !Ref HttpApi
            Method: post
            Path: /
          Type: HttpApi
      FunctionName: !Sub "${StackName}-webhook"
      Handler: app.handler
      Runtime: python3.12
      Timeout: 15
      Tags:
        resource-name: !Ref StackName

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: >
        API Gateway for webhook function
      Name: !Sub "${StackName}-api-gateway"
      StageName: "prod"
      Tags:
        resource-name: !Ref StackName
